title: "QADL Project"
description: "A formalized approach to designing quantum systems"
theme: jekyll-theme-cayman
baseurl: ""
url: "https://wasimsse.github.io/QADL"  # Update this with your GitHub username and repository
